num1=float(input("Primer número: "))
num2=float(input("Segundo número: "))
print("Suma ", num1 + num2)
print("Resta ", num1 - num2)
print("Multiplicación ", num1 * num2)
print("Divición ", num1 / num2)
print("Potencia ", num1 ** num2)
print("Suelo ", num1 // num2)
print("Módulo ", num1 % num2)